version: '3.0'
services:
  usecase:
    image: joeydewaal/usecase
    env_file:
      - .env
    environment:
      - APIKEY = ${APIKEY}
      - TB_ACCESSTOKEN = ${TB_ACCESSTOKEN}
  mytb:
    restart: always
    image: joeydewaal/tb-base
    ports:
      - "8080:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - ~/.mytb-data:/data
      - ~/.mytb-logs:/var/log/thingsboard
