- name: Install docker and docker-compose
  become: yes 
  apt:
    name: docker-compose
    state: latest

- name: Install pip
  become: yes 
  apt:
    name: pip
    state: latest

- name: Install Docker Module for Python
  become: yes 
  pip:
    name: docker

- name: Install git
  become: yes 
  apt:
    name: git
    state: latest
