- name: show os family
  ansible.builtin.debug:
    msg: "{{  ansible_facts['os_family']|lower }}"


- name: Import tasks for redhat
  import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'rocky'

- name: Import tasks for debian
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'



- name: get the username running the deploy
  become: false
  local_action: command whoami
  register: username

- name: show username
  ansible.builtin.debug:
    msg: "{{ username.stdout }}"

    #- copy:
    #src:  "~/.ssh/id_rsa"
    #dest: "/home/{{ username.stdout }}/id_rsa"
    #owner: "{{ username.stdout }}"
    #mode: "0400"

    #- name: Cloning repo
    #ansible.builtin.git:
    #key_file: "/home/{{ username.stdout }}/id_rsa"
    #repo: git@github.com:JoeydeWaal1/IAC.git
    #dest: "/home/{{ username.stdout }}/IAC"
    #clone: yes

- name: docker compose
  community.docker.docker_compose:
    project_name: project_IAC
    definition:
      version: '3.0'
      services:
        usecase:
          image: joeydewaal/usecase
          env_file:
            - .env
          environment:
            - APIKEY = "{{ api_key }}"
            - TB_ACCESSTOKEN = Q537PNgCtg92vhOF0MW1
          networks:
            - network1
        mytb:
          restart: always
          image: joeydewaal/tb-base
          ports:
            - "8080:9090"
            - "1883:1883"
            - "7070:7070"
            - "5683-5688:5683-5688/udp"
          environment:
            TB_QUEUE_TYPE: in-memory
          volumes:
            - ~/.mytb-data:/data
            - ~/.mytb-logs:/var/log/thingsboard
          networks:
            - network1
        networks:
          network1:
            name: net
