- name: Install yum-utils
  ansible.builtin.yum:
    name: yum-utils
    state: present

- name: Add repository into repo.d list
  ansible.builtin.yum_repository:
    name: docker
    description: docker repository
    baseurl: "https://download.docker.com/linux/centos/$releasever/$basearch/stable"
    enabled: true
    gpgcheck: true
    gpgkey: "https://download.docker.com/linux/centos/gpg"

- name: Install Docker
  #ignore_errors: true
  ansible.builtin.yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest

- name: Start Docker
  ansible.builtin.service:
    name: "docker"
    enabled: true
    state: started

- name: install python
  ansible.builtin.package:
    name: python
    state: present

- name: install pip
  ansible.builtin.package:
    name: python-pip
    state: present

- name: install docker-py
  ansible.builtin.pip:
    name: docker-py

- name: Install git
  ansible.builtin.yum:
    name: yum-utils
    state: present
