- import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'rocky'

- import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

- become: true
  community.docker.docker_network:
    name: net

- name: start Thingsboard container
  become: true
  community.docker.docker_container:
    name: thingsboard
    image: joeydewaal/thingsboard
    ports:
      - "{{ api_port }}:9090"
    networks:
      - name: net
    restart_policy: always

- name: start usecase container
  become: true
  community.docker.docker_container:
    name: usecase
    image: joeydewaal/usecase
    env:
      APIKEY="{{ api_key }}"
    networks:
      - name: net
    restart_policy: always
