- name: show os family
  ansible.builtin.debug:
    msg: "{{  ansible_facts['os_family']|lower }}" 

#os specific
- name: Import tasks for redhat
  import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'rocky'

- name: Import tasks for debian
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

  #- name: change groups
  #become: true
  #shell: usermod -aG docker $USER


- name: get the username running the deploy
  become: false
  local_action: command whoami
  register: username

- name: add docker network
  become: true
  community.docker.docker_network:
    name: net

- name: Thingsboard
  become: true
  community.docker.docker_container:
    name: thingsboard
    image: joeydewaal/thingsboard
    ports:
      - "8080:9090"
    networks:
      - name: net
    restart_policy: always
- name: usecase
  become: true
  community.docker.docker_container:
    name: usecase
    image: joeydewaal/usecase
    env:
      APIKEY="{{ api_key }}"
    networks:
      - name: net
    restart_policy: always
