- name: close udp ports
  become: true
  ansible.posix.firewalld:
    port: 0-65535/udp
    permanent: true
    state: disabled

- name: close tcp ports
  become: true
  ansible.posix.firewalld:
    port: 0-65535/tcp
    permanent: true
    state: disabled

- name: "Allow port {{ api_port }} (port of the server)"
  become: true
  ansible.posix.firewalld:
    port: "{{ api_port }}/tcp"
    permanent: true
    state: enabled

- name: Install yum-utils
  become: yes
  ansible.builtin.yum:
    name: yum-utils
    state: present

- become: yes
  ansible.builtin.yum_repository:
    name: docker
    description: docker repository
    baseurl: "https://download.docker.com/linux/centos/$releasever/$basearch/stable"
    enabled: true
    gpgcheck: true
    gpgkey: "https://download.docker.com/linux/centos/gpg"

- name: Install Docker
  become: yes
  #ignore_errors: true
  ansible.builtin.yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest

- become: yes
  ansible.builtin.service:
    name: "docker"
    enabled: true
    state: started

- become: yes
  ansible.builtin.package:
    name: python3
    state: present

- become: yes
  ansible.builtin.yum:
    name: epel-release
    state: present

- become: yes
  ansible.builtin.yum:
    name: '*'
    state: latest

- become: yes
  ansible.builtin.yum:
    name: python3-pip
    state: present

- become: yes
  ansible.builtin.pip:
    name: docker-py
