- name: Install yum-utils
  become: yes
  ansible.builtin.yum:
    name: yum-utils
    state: present

- name: Add repository into repo.d list
  become: yes
  ansible.builtin.yum_repository:
    name: docker
    description: docker repository
    baseurl: "https://download.docker.com/linux/centos/$releasever/$basearch/stable"
    enabled: true
    gpgcheck: true
    gpgkey: "https://download.docker.com/linux/centos/gpg"

- name: Install Docker
  become: yes
  #ignore_errors: true
  ansible.builtin.yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest

- name: Start Docker
  become: yes
  ansible.builtin.service:
    name: "docker"
    enabled: true
    state: started

- name: install python
  become: yes
  ansible.builtin.package:
    name: python3
    state: present

- name: install epel
  become: yes
  ansible.builtin.yum:
    name: epel-release
    state: present

- name: Upgrade all packages
  become: yes
  ansible.builtin.yum:
    name: '*'
    state: latest

- name: install pip
  become: yes
  ansible.builtin.yum:
    name: python3-pip
    state: present

- name: install docker-py
  become: yes
  ansible.builtin.pip:
    name: docker-py
